apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kitchensink-app-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: kitchensink
      name: kitchensink
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/kitchensink-app/kitchensink:latest
              imagePullPolicy: Always
              name: kitchensink
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
          securityContext: {}
    status: {}
parameters: []
